[package]
name = "payroll-app"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
payroll = { path = "../payroll" }

[dev-dependencies]
sqlx = { version = "0.8", default-features = false, features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "macros",
    "migrate",
] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
